name: poc_faker
channels:
  - conda-forge
dependencies:
  - python=3.11
  - faker
  - pyarrow
  - pandas
  - pyyaml
  - snowflake-snowpark-python
  - pydantic
  - pip
  - pip:
    - "snowflake-connector-python[secure-local-storage,pandas]"
